bundle:
  groupId: "io.jenkins.tools.custom-war-packager.it.pom-with-maven-info-source"
  artifactId: "pom-with-maven-info-source"
  title: "CWP Integration Test for POM input with Maven Info input source"
buildSettings:
  pom: pom.xml
  pomUseMavenPluginInfoProvider: true
  pomIgnoreRoot: true
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: 2.176.1
casc:
  - id: "casc"
    source:
      dir: casc.yml
